[project]
name = "metrix-analysis"
version = "0.1.0"
description = ""
authors = [{ name = "Alonso Villegas", email = "emptysoda16@gmail.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
dependencies = [
    "scikit-learn>=1.5.0,<2",
    "xgboost>=2.0.3,<3",
    "joblib>=1.4.2,<2",
    "tensorflow>=2.19.0,<3",
    "tf-keras>=2.19.0,<3",
    "evaluate>=0.4.3,<0.5",
    "datasets>=2.21.0",
    "accelerate>=1.6.0",
    "transformers>=4.51.3",
    "optune>=0.1.1",
    "optuna>=4.3.0",
    "iapucp-metrix>=0.1.0",
    "matplotlib>=3.8.0",
]

[dependency-groups]
dev = ["huggingface-hub[cli]>=0.30.1,<0.31"]
